/**
 * @file lib/pdf/template.ts
 * @description PDF generation template or style definition for exports (template).
 */

import { PDF_STYLES } from "./styles"

export function generatePdfHtml(
  projectName: string,
  headersHtml: string,
  rowsHtml: string,
  selectedCount: number
): string {
  const logoUrl = typeof window !== "undefined" ? `${window.location.origin}/logo-horizontal.png` : "/logo-horizontal.png"
  const logoHtml = `
    <img src="${logoUrl}" height="36" alt="gluvok logo" style="object-fit: contain;" />
  `
  return `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${projectName} Export</title>
        <style>${PDF_STYLES}</style>
      </head>
      <body>
        <header>
          <div class="brand">
            ${logoHtml}
          </div>
          <div class="meta">
            Document: <span class="meta-value">${projectName} Export</span><br>
            Date: <span class="meta-value">${new Date().toLocaleDateString()}</span><br>
            Total Records: <span class="meta-value">${selectedCount}</span>
          </div>
        </header>
        <table>
          <thead>
            <tr>${headersHtml}</tr>
          </thead>
          <tbody>
            ${rowsHtml}
          </tbody>
        </table>
        <footer>
          Generated by Gluvok - By Lathey Weigh Trix.
        </footer>
      </body>
    </html>
  `
}
