export enum State {
  AN = "Andaman and Nicobar Islands",
  AP = "Andhra Pradesh",
  AR = "Arunachal Pradesh",
  AS = "Assam",
  BR = "Bihar",
  CH = "Chandigarh",
  CG = "Chhattisgarh",
  DD = "Daman and Diu",
  DL = "Delhi",
  DN = "Dadra and Nagar Haveli and Daman and Diu",
  GA = "Goa",
  GJ = "Gujarat",
  HR = "Haryana",
  HP = "Himachal Pradesh",
  JK = "Jammu and Kashmir",
  JH = "Jharkhand",
  KA = "Karnataka",
  KL = "Kerala",
  LA = "Ladakh",
  LD = "Lakshadweep",
  MP = "Madhya Pradesh",
  MH = "Maharashtra",
  MN = "Manipur",
  ML = "Meghalaya",
  MZ = "Mizoram",
  NL = "Nagaland",
  OD = "Odisha",
  PY = "Puducherry",
  PB = "Punjab",
  RJ = "Rajasthan",
  SK = "Sikkim",
  TN = "Tamil Nadu",
  TS = "Telangana",
  TR = "Tripura",
  UP = "Uttar Pradesh",
  UK = "Uttarakhand",
  WB = "West Bengal",
}

export enum CommodityName {
  WHEAT = "Wheat",
  SCRAP_COPPER = "Scrap Copper",
  CORN = "Corn",
  CRUDE_OIL = "Crude Oil",
}

export enum Role {
  ADMIN = "Admin",
  OPERATOR = "Operator",
  MANAGER = "Manager",
  AUTHENTICATED = "authenticated",
}

export enum ColumnLabel {
  ID = "ID",
  GOVT_ID = "Govt ID",
  AADHAR_NUMBER = "Aadhar Number",
  NAME = "Name",
  STATE = "State",
  FACTORY_ID = "Factory ID",
  UNIT_PRICE = "Unit Price",
  FATHER_NAME = "Father's Name",
  VILLAGE_ID = "Village ID",
  VEHICLE_NUMBER = "Vehicle Number",
  WEIGHT = "Weight",
  COMMODITY_ID = "Commodity ID",
  CENTER_ID = "Center ID",
  OPERATOR_ID = "Operator ID",
  CUSTOMER_ID = "Customer ID",
  EMAIL = "Email",
  ROLE = "Role",
  CREATED_AT = "Created At",
  UPDATED_AT = "Updated At",
}

